export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_BOUGHT_PRODUCT = 'ADD_BOUGHT_PRODUCT';

export const FETCH_PRODUCT_CATEGORY_SUCCESS = 'FETCH_PRODUCT_CATEGORY_SUCCESS';

export const CLEAR_SHOPPING_LIST = 'CLEAR_SHOPPING_LIST';